# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.27.6-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.27.6-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/humberto/repository/OpenMugen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/humberto/repository/OpenMugen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/cmake-3.27.6-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.27.6-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/humberto/repository/OpenMugen/CMakeFiles /home/humberto/repository/OpenMugen//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/humberto/repository/OpenMugen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenMugen

# Build rule for target.
OpenMugen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenMugen
.PHONY : OpenMugen

# fast build rule for target.
OpenMugen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/build
.PHONY : OpenMugen/fast

src/AirManager.o: src/AirManager.cpp.o
.PHONY : src/AirManager.o

# target to build an object file
src/AirManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/AirManager.cpp.o
.PHONY : src/AirManager.cpp.o

src/AirManager.i: src/AirManager.cpp.i
.PHONY : src/AirManager.i

# target to preprocess a source file
src/AirManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/AirManager.cpp.i
.PHONY : src/AirManager.cpp.i

src/AirManager.s: src/AirManager.cpp.s
.PHONY : src/AirManager.s

# target to generate assembly for a file
src/AirManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/AirManager.cpp.s
.PHONY : src/AirManager.cpp.s

src/CmdManager.o: src/CmdManager.cpp.o
.PHONY : src/CmdManager.o

# target to build an object file
src/CmdManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/CmdManager.cpp.o
.PHONY : src/CmdManager.cpp.o

src/CmdManager.i: src/CmdManager.cpp.i
.PHONY : src/CmdManager.i

# target to preprocess a source file
src/CmdManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/CmdManager.cpp.i
.PHONY : src/CmdManager.cpp.i

src/CmdManager.s: src/CmdManager.cpp.s
.PHONY : src/CmdManager.s

# target to generate assembly for a file
src/CmdManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/CmdManager.cpp.s
.PHONY : src/CmdManager.cpp.s

src/ControllerExecuter.o: src/ControllerExecuter.cpp.o
.PHONY : src/ControllerExecuter.o

# target to build an object file
src/ControllerExecuter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/ControllerExecuter.cpp.o
.PHONY : src/ControllerExecuter.cpp.o

src/ControllerExecuter.i: src/ControllerExecuter.cpp.i
.PHONY : src/ControllerExecuter.i

# target to preprocess a source file
src/ControllerExecuter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/ControllerExecuter.cpp.i
.PHONY : src/ControllerExecuter.cpp.i

src/ControllerExecuter.s: src/ControllerExecuter.cpp.s
.PHONY : src/ControllerExecuter.s

# target to generate assembly for a file
src/ControllerExecuter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/ControllerExecuter.cpp.s
.PHONY : src/ControllerExecuter.cpp.s

src/Input.o: src/Input.cpp.o
.PHONY : src/Input.o

# target to build an object file
src/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/Input.cpp.o
.PHONY : src/Input.cpp.o

src/Input.i: src/Input.cpp.i
.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s
.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/MemManager.o: src/MemManager.cpp.o
.PHONY : src/MemManager.o

# target to build an object file
src/MemManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/MemManager.cpp.o
.PHONY : src/MemManager.cpp.o

src/MemManager.i: src/MemManager.cpp.i
.PHONY : src/MemManager.i

# target to preprocess a source file
src/MemManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/MemManager.cpp.i
.PHONY : src/MemManager.cpp.i

src/MemManager.s: src/MemManager.cpp.s
.PHONY : src/MemManager.s

# target to generate assembly for a file
src/MemManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/MemManager.cpp.s
.PHONY : src/MemManager.cpp.s

src/SDLManager.o: src/SDLManager.cpp.o
.PHONY : src/SDLManager.o

# target to build an object file
src/SDLManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SDLManager.cpp.o
.PHONY : src/SDLManager.cpp.o

src/SDLManager.i: src/SDLManager.cpp.i
.PHONY : src/SDLManager.i

# target to preprocess a source file
src/SDLManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SDLManager.cpp.i
.PHONY : src/SDLManager.cpp.i

src/SDLManager.s: src/SDLManager.cpp.s
.PHONY : src/SDLManager.s

# target to generate assembly for a file
src/SDLManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SDLManager.cpp.s
.PHONY : src/SDLManager.cpp.s

src/SDL_framerate.o: src/SDL_framerate.cpp.o
.PHONY : src/SDL_framerate.o

# target to build an object file
src/SDL_framerate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SDL_framerate.cpp.o
.PHONY : src/SDL_framerate.cpp.o

src/SDL_framerate.i: src/SDL_framerate.cpp.i
.PHONY : src/SDL_framerate.i

# target to preprocess a source file
src/SDL_framerate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SDL_framerate.cpp.i
.PHONY : src/SDL_framerate.cpp.i

src/SDL_framerate.s: src/SDL_framerate.cpp.s
.PHONY : src/SDL_framerate.s

# target to generate assembly for a file
src/SDL_framerate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SDL_framerate.cpp.s
.PHONY : src/SDL_framerate.cpp.s

src/SffManager.o: src/SffManager.cpp.o
.PHONY : src/SffManager.o

# target to build an object file
src/SffManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SffManager.cpp.o
.PHONY : src/SffManager.cpp.o

src/SffManager.i: src/SffManager.cpp.i
.PHONY : src/SffManager.i

# target to preprocess a source file
src/SffManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SffManager.cpp.i
.PHONY : src/SffManager.cpp.i

src/SffManager.s: src/SffManager.cpp.s
.PHONY : src/SffManager.s

# target to generate assembly for a file
src/SffManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/SffManager.cpp.s
.PHONY : src/SffManager.cpp.s

src/Stack.o: src/Stack.cpp.o
.PHONY : src/Stack.o

# target to build an object file
src/Stack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/Stack.cpp.o
.PHONY : src/Stack.cpp.o

src/Stack.i: src/Stack.cpp.i
.PHONY : src/Stack.i

# target to preprocess a source file
src/Stack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/Stack.cpp.i
.PHONY : src/Stack.cpp.i

src/Stack.s: src/Stack.cpp.s
.PHONY : src/Stack.s

# target to generate assembly for a file
src/Stack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/Stack.cpp.s
.PHONY : src/Stack.cpp.s

src/StateManager.o: src/StateManager.cpp.o
.PHONY : src/StateManager.o

# target to build an object file
src/StateManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/StateManager.cpp.o
.PHONY : src/StateManager.cpp.o

src/StateManager.i: src/StateManager.cpp.i
.PHONY : src/StateManager.i

# target to preprocess a source file
src/StateManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/StateManager.cpp.i
.PHONY : src/StateManager.cpp.i

src/StateManager.s: src/StateManager.cpp.s
.PHONY : src/StateManager.s

# target to generate assembly for a file
src/StateManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/StateManager.cpp.s
.PHONY : src/StateManager.cpp.s

src/StateParser.o: src/StateParser.cpp.o
.PHONY : src/StateParser.o

# target to build an object file
src/StateParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/StateParser.cpp.o
.PHONY : src/StateParser.cpp.o

src/StateParser.i: src/StateParser.cpp.i
.PHONY : src/StateParser.i

# target to preprocess a source file
src/StateParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/StateParser.cpp.i
.PHONY : src/StateParser.cpp.i

src/StateParser.s: src/StateParser.cpp.s
.PHONY : src/StateParser.s

# target to generate assembly for a file
src/StateParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/StateParser.cpp.s
.PHONY : src/StateParser.cpp.s

src/VM.o: src/VM.cpp.o
.PHONY : src/VM.o

# target to build an object file
src/VM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/VM.cpp.o
.PHONY : src/VM.cpp.o

src/VM.i: src/VM.cpp.i
.PHONY : src/VM.i

# target to preprocess a source file
src/VM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/VM.cpp.i
.PHONY : src/VM.cpp.i

src/VM.s: src/VM.cpp.s
.PHONY : src/VM.s

# target to generate assembly for a file
src/VM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/VM.cpp.s
.PHONY : src/VM.cpp.s

src/VideoSystem.o: src/VideoSystem.cpp.o
.PHONY : src/VideoSystem.o

# target to build an object file
src/VideoSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/VideoSystem.cpp.o
.PHONY : src/VideoSystem.cpp.o

src/VideoSystem.i: src/VideoSystem.cpp.i
.PHONY : src/VideoSystem.i

# target to preprocess a source file
src/VideoSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/VideoSystem.cpp.i
.PHONY : src/VideoSystem.cpp.i

src/VideoSystem.s: src/VideoSystem.cpp.s
.PHONY : src/VideoSystem.s

# target to generate assembly for a file
src/VideoSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/VideoSystem.cpp.s
.PHONY : src/VideoSystem.cpp.s

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/global.o: src/global.cpp.o
.PHONY : src/global.o

# target to build an object file
src/global.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/global.cpp.o
.PHONY : src/global.cpp.o

src/global.i: src/global.cpp.i
.PHONY : src/global.i

# target to preprocess a source file
src/global.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/global.cpp.i
.PHONY : src/global.cpp.i

src/global.s: src/global.cpp.s
.PHONY : src/global.s

# target to generate assembly for a file
src/global.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/global.cpp.s
.PHONY : src/global.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/scale2x.o: src/scale2x.cpp.o
.PHONY : src/scale2x.o

# target to build an object file
src/scale2x.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/scale2x.cpp.o
.PHONY : src/scale2x.cpp.o

src/scale2x.i: src/scale2x.cpp.i
.PHONY : src/scale2x.i

# target to preprocess a source file
src/scale2x.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/scale2x.cpp.i
.PHONY : src/scale2x.cpp.i

src/scale2x.s: src/scale2x.cpp.s
.PHONY : src/scale2x.s

# target to generate assembly for a file
src/scale2x.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/scale2x.cpp.s
.PHONY : src/scale2x.cpp.s

src/scale2xSDL.o: src/scale2xSDL.cpp.o
.PHONY : src/scale2xSDL.o

# target to build an object file
src/scale2xSDL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/scale2xSDL.cpp.o
.PHONY : src/scale2xSDL.cpp.o

src/scale2xSDL.i: src/scale2xSDL.cpp.i
.PHONY : src/scale2xSDL.i

# target to preprocess a source file
src/scale2xSDL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/scale2xSDL.cpp.i
.PHONY : src/scale2xSDL.cpp.i

src/scale2xSDL.s: src/scale2xSDL.cpp.s
.PHONY : src/scale2xSDL.s

# target to generate assembly for a file
src/scale2xSDL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/scale2xSDL.cpp.s
.PHONY : src/scale2xSDL.cpp.s

src/tokenizer.o: src/tokenizer.cpp.o
.PHONY : src/tokenizer.o

# target to build an object file
src/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/tokenizer.cpp.o
.PHONY : src/tokenizer.cpp.o

src/tokenizer.i: src/tokenizer.cpp.i
.PHONY : src/tokenizer.i

# target to preprocess a source file
src/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/tokenizer.cpp.i
.PHONY : src/tokenizer.cpp.i

src/tokenizer.s: src/tokenizer.cpp.s
.PHONY : src/tokenizer.s

# target to generate assembly for a file
src/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenMugen.dir/build.make CMakeFiles/OpenMugen.dir/src/tokenizer.cpp.s
.PHONY : src/tokenizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OpenMugen"
	@echo "... src/AirManager.o"
	@echo "... src/AirManager.i"
	@echo "... src/AirManager.s"
	@echo "... src/CmdManager.o"
	@echo "... src/CmdManager.i"
	@echo "... src/CmdManager.s"
	@echo "... src/ControllerExecuter.o"
	@echo "... src/ControllerExecuter.i"
	@echo "... src/ControllerExecuter.s"
	@echo "... src/Input.o"
	@echo "... src/Input.i"
	@echo "... src/Input.s"
	@echo "... src/MemManager.o"
	@echo "... src/MemManager.i"
	@echo "... src/MemManager.s"
	@echo "... src/SDLManager.o"
	@echo "... src/SDLManager.i"
	@echo "... src/SDLManager.s"
	@echo "... src/SDL_framerate.o"
	@echo "... src/SDL_framerate.i"
	@echo "... src/SDL_framerate.s"
	@echo "... src/SffManager.o"
	@echo "... src/SffManager.i"
	@echo "... src/SffManager.s"
	@echo "... src/Stack.o"
	@echo "... src/Stack.i"
	@echo "... src/Stack.s"
	@echo "... src/StateManager.o"
	@echo "... src/StateManager.i"
	@echo "... src/StateManager.s"
	@echo "... src/StateParser.o"
	@echo "... src/StateParser.i"
	@echo "... src/StateParser.s"
	@echo "... src/VM.o"
	@echo "... src/VM.i"
	@echo "... src/VM.s"
	@echo "... src/VideoSystem.o"
	@echo "... src/VideoSystem.i"
	@echo "... src/VideoSystem.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/scale2x.o"
	@echo "... src/scale2x.i"
	@echo "... src/scale2x.s"
	@echo "... src/scale2xSDL.o"
	@echo "... src/scale2xSDL.i"
	@echo "... src/scale2xSDL.s"
	@echo "... src/tokenizer.o"
	@echo "... src/tokenizer.i"
	@echo "... src/tokenizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

