name: CD

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

# required for upload
permissions:
  contents: write

jobs:

  Linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-24.04, ubuntu-24.04-arm ]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y libsdl2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev libsdl1.2-compat build-essential cmake make

      - name: Build tar.gz
        run: make clean targz/data build targz/openmugen

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.tar.gz


  MacOS:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ macos-latest, macos-13 ]
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: brew install sdl2 sdl_image sdl_gfx sdl12-compat cmake make

      - name: Build tar.gz
        run: make clean targz/data build targz/openmugen

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.tar.gz            
